apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-queue
  template:
    metadata:
      labels:
        app: job-queue
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
            # requests:
            #   memory: "1Gi" # Minimum recommended
            #   cpu: "500m"
            # limits:
            #   memory: "2Gi" # Better for production
            #   cpu: "1000m" # RabbitMQ benefits from more CPU
          ports:
            - containerPort: 5672 # AMQP
            - containerPort: 15672 # Management UI
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: job-queue
spec:
  type: LoadBalancer
  selector:
    app: job-queue
  ports:
    - name: amqp
      port: 5673
      targetPort: 5672
    - name: management
      port: 15673
      targetPort: 15672
