apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-queue
  template:
    metadata:
      labels:
        app: pipeline-queue
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          resources:
            requests:
              memory: "64Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
          ports:
            - containerPort: 5672 # AMQP
            - containerPort: 15672 # Management UI
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-queue
spec:
  type: LoadBalancer
  selector:
    app: pipeline-queue
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
