apiVersion: apps/v1
kind: Deployment
metadata:
  name: pool-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pool-api
  template:
    metadata:
      labels:
        app: pool-api
    spec:
      containers:
        - name: pool-api
          image: minh160302/pool-api
          env:
            # MySQL
            - name: DB_HOST
              value: mycluster
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mycluster-cluster-secret
                  key: rootUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mycluster-cluster-secret
                  key: rootPassword
            - name: DB_NAME
              value: CicdApplication
            # GitHub
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: token
            # MinIO
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-keys
                  key: CONSOLE_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-keys
                  key: CONSOLE_SECRET_KEY
            - name: MINIO_ENDPOINT
              value: minio.default.svc.cluster.local
            - name: DEFAULT_BUCKET
              value: default
            # RabbitMQ
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672/
            - name: TASK_QUEUE
              value: task_queue
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
---
apiVersion: v1
kind: Service
metadata:
  name: pool-api-service
spec:
  selector:
    app: pool-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
