#### failed to create pod: pods is forbidden: 
#### User "system:serviceaccount:default:default" cannot create resource "pods" in API group "" in the namespace "default"
#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: <new-account-name>
#  namespace: <namespace>

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io


# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: rbac
# subjects:
#   - kind: ServiceAccount
#     name: default
#     namespace: default
#   - kind: ServiceAccount
#     name: mycluster-sa
#     namespace: default  # Ensure this matches the namespace of your service account
# roleRef:
#   kind: ClusterRole
#   name: cluster-admin
#   apiGroup: rbac.authorization.k8s.io
