version: v0

# Pipeline info
pipeline:
  name: pipeline-name

# List of stages - show order of execution
stages:
  - build
  - test
  - docs

# Stages defined below
jobs:
  # build
  - name: compile
    stage: build
    image: maven
    script:
      - mvn clean install

  # test
  - name: run-test
    stage: test
    image: maven
    script:
      - mvn test
    needs:
      - check-coverage

  - name: check-coverage
    stage: test
    image: maven
    script:
      - mvn verify
      - mvn jacoco:report
    needs:
      - run-test # Job dependency within a stage.

  - name: checkstyle
    stage: test
    image: maven
    script:
      - mvn checkstyle:check
      - mvn checkstyle:checkstyle
    needs:
      - run-test

  # docs
  - name: documentation-job-1-name
    stage: docs
    image: maven
    script:
      - ls -la
      - mvn javadoc:javadoc
