name: Build CI

on:
  pull_request:
  push:
    branches:
      - main
    path:
      - "!dev-docs/**"
      - "!README.md"
  workflow_call:
    inputs:
      tag:
        description: "Tag for Go project build workflow"
        required: true
        type: string

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.60

defaults:
  run:
    shell: bash
    working-directory: ./CLI

jobs:
  ### CLI codebase
  cli-test:
    name: CLI - Test and Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./CLI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Generate executable
        run: chmod +x coverage.sh
      - name: Run
        run: |
          go mod tidy
          ./coverage.sh > ./reports/test-summary.txt
      ####
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: TestReports
          path: ./CLI/reports/*

  cli-build:
    needs: cli-test
    name: CLI - Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build code
        run: |
          go mod tidy
          go build

  cli-golangci-lint:
    name: CLI - Run Lint
    runs-on: ubuntu-latest
    needs: cli-build
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-
      - name: Cache golangci-lint
        uses: actions/cache@v4
        with:
          path: ~/.cache/golangci-lint
          key: golangci-${{ runner.os }}-${{ hashFiles('.github/workflows/ci.yaml') }}
          restore-keys: |
            golangci-${{ runner.os }}-
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run golangci-lint
        run: golangci-lint run --config=.golangci.yaml

  ### backend codebase
  backend-test:
    name: backend - Test and Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Generate executable
        run: chmod +x coverage.sh
      - name: Create Env var
        run: 'echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" '
      - name: Run
        run: |
          go mod download
          ./coverage.sh > ./reports/test-summary.txt
      ####
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: TestReports
          path: ./backend/reports/*

  backend-build:
    needs: backend-test
    name: backend - Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
      - name: Build code
        run: |
          go mod download
          go build

  backend-golangci-lint:
    name: backend - Run Lint
    runs-on: ubuntu-latest
    needs: backend-build
    continue-on-error: true
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-
      - name: Cache golangci-lint
        uses: actions/cache@v4
        with:
          path: ~/.cache/golangci-lint
          key: golangci-${{ runner.os }}-${{ hashFiles('.github/workflows/ci.yaml') }}
          restore-keys: |
            golangci-${{ runner.os }}-
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run golangci-lint
        run: golangci-lint run --config=.golangci.yaml
