name: Build CI

on:
  pull_request:
  push:
    branches:
      - main
    path:
      - "!dev-docs/**"
      - "!README.md"
  workflow_call:
    inputs:
      tag:
        description: "Tag for Go project build workflow"
        required: true
        type: string

env:
  GO_VERSION: "1.23.6"
  GOLANGCI_LINT_VERSION: v1.63.4

jobs:
  ### Upload SQL init file
  upload-sql:
    name: Upload SQL File
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload SQL file
        uses: actions/upload-artifact@v4
        with:
          name: sql-init
          path: ./backend/db/init.sql

  ### CLI codebase
  cli-test:
    if: github.event.pull_request.draft == false # Skip CI for draft PRs
    name: CLI - Test and Coverage
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: CicdApplication
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: localhost
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MINIO_ENDPOINT: localhost:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      DEFAULT_BUCKET: test-bucket
      REDIS_USERNAME: default
      REDIS_PASSWORD: password
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli --user default --pass password ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          REDIS_USER: default
          REDIS_PASSWORD: password
    defaults:
      run:
        shell: bash
        working-directory: ./CLI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # Ensure full history is available
      - name: Verify Git commit
        run: git rev-parse HEAD
      # MinIO
      - name: Start MinIO in Background
        run: |
          docker run -d \
            -p 9000:9000 \
            -p 9001:9001 \
            --name minio \
            -v $HOME/minio/data:/data \
            -e "MINIO_ROOT_USER=minioadmin" \
            -e "MINIO_ROOT_PASSWORD=minioadmin" \
            quay.io/minio/minio server /data --console-address ":9001"
      # RabbitMQ
      - name: Start RabbitMQ in Background
        run: docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:4.0-management
      # Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      # MySQL
      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      # Redis
      - name: Start Redis
        run: docker run -d --name redis -p 6379:6379 -e REDIS_PASSWORD=${{ env.REDIS_PASSWORD }} redis:alpine /bin/sh -c 'redis-server --requirepass "$$REDIS_PASSWORD"'
      - name: Apply SQL File
        working-directory: ./backend # Change if your SQL file is elsewhere
        run: ls && mysql -u root -p"${{ env.DB_PASSWORD }}" ${{ env.DB_DATABASE }} < ./db/init.sql
      # Run tests
      - name: Run local api for CLI testing
        working-directory: ./backend
        run: |
          go mod tidy
          nohup go run . > ../server.log 2>&1 &  # Run the Go application in the background
          # Wait until the server is ready to accept requests
          until curl -s http://localhost:8080 > /dev/null; do
            echo "Waiting for server to start..."
            sleep 1  # Wait for 1 second before trying again
          done
          echo "Server is up, making the request..."
          curl http://localhost:8080

      - name: Generate executable
        run: chmod +x coverage.sh
      - name: Install dependecies
        run: go mod tidy
      - name: Run Tests
        run: go test -v ./... -coverpkg=./... -coverprofile=./cover.out
      - name: Get Docker logs
        run: docker ps -aq | xargs -I {} docker logs {}
      - name: Generate coverage report
        run: ./coverage.sh > ./reports/test-summary.txt
      #### Upload
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: CLI_TestReports
          path: ./CLI/reports/*

  cli-build:
    needs: cli-test
    name: CLI - Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./CLI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build code
        run: |
          go mod tidy
          go build

  cli-golangci-lint:
    name: CLI - Run Lint
    runs-on: ubuntu-latest
    needs: cli-build
    continue-on-error: true
    defaults:
      run:
        shell: bash
        working-directory: ./CLI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-
      - name: Cache golangci-lint
        uses: actions/cache@v4
        with:
          path: ~/.cache/golangci-lint
          key: golangci-${{ runner.os }}-${{ hashFiles('.github/workflows/ci.yaml') }}
          restore-keys: |
            golangci-${{ runner.os }}-
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run golangci-lint
        run: golangci-lint run --config=.golangci.yaml

  ### backend codebase
  backend-test:
    if: github.event.pull_request.draft == false # Skip CI for draft PRs
    name: backend - Test and Coverage
    runs-on: ubuntu-latest
    needs: upload-sql
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    env:
      DB_DATABASE: CicdApplication
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: localhost
      RABBITMQ_URL: amqp://guest:guest@localhost:5672/
      TASK_QUEUE: task_queue
      REDIS_USERNAME: default
      REDIS_PASSWORD: password
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      # MySQL
      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      # RabbitMQ
      - name: Start RabbitMQ in Background
        run: docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:4.0-management
      # Redis
      - name: Start Redis
        run: docker run -d --name redis -p 6379:6379 -e REDIS_PASSWORD=${{ env.REDIS_PASSWORD }} redis:alpine /bin/sh -c 'redis-server --requirepass "$$REDIS_PASSWORD"'
      # Download and apply SQL file
      - name: Download SQL file
        uses: actions/download-artifact@v4
        with:
          name: sql-init
          path: ./backend/db/
      - name: Apply SQL File
        working-directory: ./backend # Change if your SQL file is elsewhere
        run: mysql -u root -p"${{ env.DB_PASSWORD }}" ${{ env.DB_DATABASE }} < ./db/init.sql
      - name: Generate executable
        run: chmod +x coverage.sh
      - name: Create Env var
        run: 'echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" && echo "DB_PASSWORD=${{ env.DB_PASSWORD }}"'
      - name: Install dependencies
        run: go mod tidy
      - name: Run test
        run: go test -v ./... -coverpkg=./... -coverprofile=./cover.out
      - name: Generate coverage reports
        run: pwd && ./coverage.sh > ./reports/test-summary.txt
      ####
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: backend_TestReports
          path: ./backend/reports/*

  backend-build:
    needs: backend-test
    name: backend - Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build code
        run: |
          go mod download
          go build

  backend-golangci-lint:
    name: backend - Run Lint
    runs-on: ubuntu-latest
    needs: backend-build
    continue-on-error: true
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-
      - name: Cache golangci-lint
        uses: actions/cache@v4
        with:
          path: ~/.cache/golangci-lint
          key: golangci-${{ runner.os }}-${{ hashFiles('.github/workflows/ci.yaml') }}
          restore-keys: |
            golangci-${{ runner.os }}-
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run golangci-lint
        run: golangci-lint run --config=.golangci.yaml

  ### worker codebase
  worker-test:
    if: github.event.pull_request.draft == false # Skip CI for draft PRs
    name: worker - Test and Coverage
    runs-on: ubuntu-latest
    needs: upload-sql

    defaults:
      run:
        shell: bash
        working-directory: ./worker
    env:
      DB_DATABASE: CicdApplication
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: localhost
      MINIO_ENDPOINT: localhost:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      DEFAULT_BUCKET: test-bucket
      RABBITMQ_URL: amqp://guest:guest@localhost:5672/
      TASK_QUEUE: task_queue
      REDIS_USERNAME: default
      REDIS_PASSWORD: password
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      # MinIO
      - name: Start MinIO in Background
        run: |
          docker run -d \
            -p 9000:9000 \
            -p 9001:9001 \
            --name minio \
            -v $HOME/minio/data:/data \
            -e "MINIO_ROOT_USER=minioadmin" \
            -e "MINIO_ROOT_PASSWORD=minioadmin" \
            quay.io/minio/minio server /data --console-address ":9001"
      # RabbitMQ
      - name: Start RabbitMQ in Background
        run: docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:4.0-management
      # MySQL
      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      # Redis
      - name: Start Redis
        run: docker run -d --name redis -p 6379:6379 -e REDIS_PASSWORD=${{ env.REDIS_PASSWORD }} redis:alpine /bin/sh -c 'redis-server --requirepass "$$REDIS_PASSWORD"'
      # Download and apply SQL file
      - name: Download SQL file
        uses: actions/download-artifact@v4
        with:
          name: sql-init
          path: ./worker/db/
      - name: Apply SQL File
        working-directory: ./worker # Change if your SQL file is elsewhere
        run: mysql -u root -p"${{ env.DB_PASSWORD }}" ${{ env.DB_DATABASE }} < ./db/init.sql
      - name: Generate executable
        run: chmod +x coverage.sh
      - name: Create Env var
        run: 'echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" && echo "DB_PASSWORD=${{ env.DB_PASSWORD }}"'
      - name: Install dependencies
        run: go mod tidy
      - name: Run test
        run: go test -v ./... -coverpkg=./... -coverprofile=./cover.out
      - name: Generate coverage reports
        run: pwd && ./coverage.sh > ./reports/test-summary.txt
      ####
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: worker_TestReports
          path: ./worker/reports/*

  worker-build:
    needs: worker-test
    name: worker - Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./worker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build code
        run: |
          go mod download
          go build

  worker-golangci-lint:
    name: worker - Run Lint
    runs-on: ubuntu-latest
    needs: worker-build
    continue-on-error: true
    defaults:
      run:
        shell: bash
        working-directory: ./worker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-
      - name: Cache golangci-lint
        uses: actions/cache@v4
        with:
          path: ~/.cache/golangci-lint
          key: golangci-${{ runner.os }}-${{ hashFiles('.github/workflows/ci.yaml') }}
          restore-keys: |
            golangci-${{ runner.os }}-
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run golangci-lint
        run: golangci-lint run --config=.golangci.yaml
