name: Build CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      tag:
        description: "Tag for Go project build workflow"
        required: true
        type: string

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.60

defaults:
  run:
    shell: bash
    working-directory: ./CLI

jobs:
  test:
    name: Test and Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CLI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run test and coverage script
        run: |
          go mod tidy
          echo "Tidy done"
      - name: Generate executable
        run: chmod +x script_coverage.sh
      - name: Run
        run: ./script_coverage.sh > ./reports/test-summary.txt
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: TestReports
          path: ./CLI/reports/*

  build:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build code
        run: |
          go mod tidy
          go build

  golangci-lint:
    name: Run Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: CLI

  godoc:
    needs: build
    name: Generate GoDoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Generate GoDoc
        uses: ktr0731/godoc-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
