name: Release Workflow

on:
  push:
    tags:
      - "v*.*.*" # Trigger for version tags like v1.0.0, v1.1.0

defaults:
  run:
    shell: bash
    working-directory: ./CLI

jobs:
  build:
    uses: ./.github/workflows/ci.yaml
    with:
      tag: ${{ github.ref_name }} # Pass the tag name to the build workflow

  main:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      # - name: Semantic Release
      #   uses: cycjimmy/semantic-release-action@v4
      #   with:
      #     extra_plugins: |
      #       @semantic-release/git
      #       @semantic-release/exec
      #       @semantic-release/changelog
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install Executable
        run: |
          go build
          go install .
      - name: Install GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
        run: |
          curl -sL https://git.io/goreleaser | bash

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
